version: '3.7'
services:
  db:
    # mysql:8.0（M1 Macのためにダイジェストで指定）
    image: mysql@sha256:e5dc14f6e01c3e577e669337d2855c6d1561b30d8ef2c592e63e4e8a9a52650a
    ports:
      - "13306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "hobigon"
    security_opt:
      - seccomp:unconfined
