version: '3.7'
services:
  db:
    # mysql:8.0（M1 Macのためにダイジェストで指定）
    image: mysql@sha256:cf40d2c53b86849a8d31bc5784d74a7c3a7b5545f4e5d67691ce8fa19dbf080b
    ports:
      - "13306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "hobigon"
    security_opt:
      - seccomp:unconfined
