version: '3.7'
services:
  db:
    # mysql:8.0（M1 Macのためにダイジェストで指定）
    image: mysql@sha256:932fe8fbc04c1488a38f8cab0f30cdac8d7753bded3df1762475a8001a323bc4
    ports:
      - "13306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "hobigon"
    security_opt:
      - seccomp:unconfined
