apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobigon-user-box-deployment
  labels:
    app: hobigon-user-box
  namespace: hobigon-yyh-gl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hobigon-user-box
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: hobigon-user-box
      namespace: hobigon-yyh-gl
    spec:
      containers:
        - name: hobigon-user-box
          image: ghcr.io/yyh-gl/hobigon-user-box
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/health
            periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: hobigon-user-box-service
  namespace: hobigon-yyh-gl
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: hobigon-user-box
---

# OktetoはIngressのみサポート（LoadBalancerをサポートしていない）
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    dev.okteto.com/generate-host: "true"
  name: hobigon-user-box-ingress
  namespace: hobigon-yyh-gl
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hobigon-user-box-service
                port:
                  number: 8080
