name: Scan with Detekt

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  DETEKT_RELEASE_TAG: v1.23.7

permissions:
  security-events: write

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup detekt
      uses: peter-murray/setup-detekt@v3
      with:
        detekt_version: ${{ env.DETEKT_RELEASE_TAG }}
    - name: Run Detekt
      continue-on-error: true
      run: | 
        detekt-cli --base-path . \
                   --config ./config/detekt/detekt.yml \
                   --input ${{ github.workspace }} \
                   --report sarif:${{ github.workspace }}/detekt.sarif.json
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/detekt.sarif.json

  success_notification:
    name: Success notification
    needs: [ scan ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - uses: rtCamp/action-slack-notify@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_50 }}
          SLACK_TITLE: "[hobigon-user-box] Detekt Scan Success"
        if: env.WORKFLOW_CONCLUSION == 'success'

  failure_notification:
    name: Failure notification
    needs: [ scan ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - uses: rtCamp/action-slack-notify@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_50 }}
          SLACK_TITLE: "[hobigon-user-box] Detekt Scan Failure"
          SLACK_COLOR: danger
        if: env.WORKFLOW_CONCLUSION == 'failure'
